### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by ZachZeop** [ZachZeop/FreeTime#1]
A list of things I'd like to do with this project. Some things I am confident I can do, other things are meant to be challenges for me. I will do my best to keep this page updated.

# Features:

- [ ] Find easiest way to import calendars for comparison

- [ ] Ask how many calendars need comparison

- [ ] Ask the minimum free time desired

- [ ] Compare all calendar's free time (and if free time cannot be found, with any of the user's set parameters/flags, indicate that)

- [ ] Incorporate optional, user-friendly flags on searches (all flags described below under the Flags header. Flags applied to users or optional groups)

- [ ] Group people into specific categories/types (Usage Completely Optional, meant to support easiness and user experience)

- [ ] Group timeslots into specific categories/types not already registered in their calendars [Ex: Outside office hours, Breaktime, Holiday, etc.] (Usage Completely Optional, meant to support easiness and user experience)

# Flags (Usage Completely Optional, meant to support easiness and user experience):

- [ ] Flags indicating priority of specific people's calendars over others (if more than 2 calendars are being compared)

- [ ] Flags indicating if a someone's attendance is optional (would be nice for them to be there but if not possible, don't)

- [ ] Indicate time which is technically free but unwanted for meetings (ex: middle of the night, on break, Sunday's, etc.)

# Ambitions (This is the stuff that I'll have the highest level of difficulty with):

- [ ] Use DB/GUI instead of being file/console-based

- [ ] Ensuring the program is very scalable, and can be used even on an organization-level or just between two people

- [ ] If no free time is found: ask if the user they would like to change any of their flags (maybe even suggest flags to change/add), or provide suggestions of events on different calendars to postpone in order to create time for a meeting

- [ ] Support of scheduling multiple events, or even a recurring event

- [ ] Supporting for importing/comparing from widely-used calendar applications (Google Calendar, Apple Calendar, MS Outlook Calendar, etc.), might involve implementation of OAUTH2
